RR interval:    [600, 1000]
PP interval:    [600, 1000]
PR interval:    [120, 220]
ST segment:     [80,  120]
QT interval:    [350, 440]
QTc Fridericia: [350, 450]
QTc Bazett:     [350, 450]
P duration:     [60,  120]
QRS duration:   [60,  100]
T duration:     [100, 250]
